export const SET_SELECTED_TEMPERAMENTS = 'SET_SELECTED_TEMPERAMENTS';
export const GET_ALL_DOGS = 'GET_ALL_DOGS'
export const GET_ALL_TEMPS = 'GET_ALL_TEMPS'
export const POST_DOG = 'POST_DOG'
export const GET_DOG_BY_NAME = 'GET_DOG_BY_NAME'
export const FILTER_BY_SOURCE = 'FILTER_BY_SOURCE'
export const ORDER_DOGS  = 'ORDER_DOGS '
export const POST_STATUS  = 'POST_STATUS '